### ISSUE TITLE
Adjusting dependencies to JupySQL

### ISSUE THREAD

**Issue by idomic** [sparsh-ai/recohut#32]
I think it'll be beneficial for you to use [Jupysql](https://github.com/ploomber/jupysql) in your repo as we've added support in many interactive features on top of `ipython-sql`. There's backward compatibility so it's just changing the dependency.

**Comment by sparsh-ai** [comment]
> I think it'll be beneficial for you to use [Jupysql](https://github.com/ploomber/jupysql) in your repo as we've added support in many interactive features on top of `ipython-sql`. There's backward compatibility so it's just changing the dependency.

thanks for letting me know. I went through jupysql docs. Looks interesting so far. Will try it out next time I use ipython-sql

**Comment by idomic** [comment]
Sounds good, let us know if you have any questions, here's the official note [reference](https://github.com/catherinedevlin/ipython-sql#legacy-project).
